### PR TITLE
test: fix test-process-active-wraps.js

### LINKED ISSUE #8986: test-process-active-wraps.js fails on windows
It seems that commit b636ba8186d191c52ee36f2f2b1aebbbb4d95575 introduced the following regression on Windows:
```
>.\Release\node.exe test\simple\test-process-active-
wraps.js

assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: 1 == 0
    at Immediate._onImmediate (c:\Users\jgilli\dev\node-bis\test\simple\test-pro
cess-active-wraps.js:69:16)
    at processImmediate [as _immediateCallback] (timers.js:340:17)

>
```

@cjihrig Would you mind taking a look?

### PR DESCRIPTION
**Pull request by cjihrig**
b636ba8186d191c52ee36f2f2b1aebbbb4d95575 caused a regression on Windows due to the way server handles are cleaned up. This commit fixes the test by allowing the handle to be cleaned up. Closes #8986.

cc: @piscisaureus @misterdjules

### CODE REVIEW

**Comment by piscisaureus** [comment]
LGTM, landed in b5c9dcb6d73d97eb2763e368c693da4a62b2f362

File: test/simple/test-process-active-wraps.js [hunk 1]
```diff
@@ -65,9 +65,12 @@ var handles = [];
   });
   function onclose() {
     if (++n === handles.length) {
-      setImmediate(function() {
-        assert.equal(process._getActiveHandles().length, 0);
-      });
+        // give server handle a chance to close - see GH #8986
```
Comment (misterdjules) [inline test/simple/test-process-active-wraps.js]: Do you think we could add to this comment (or at the beginning of this file, as a general comment) that this test depends a lot on the implementation of how handles are closed, and as such can and will likely break in the future? 

We could add a note saying that if the test breaks, it may be because of a correct change in the way handles are closed, and it doesn't necessarily means that node is broken.

It may save us some time next time this test breaks.

**Comment by misterdjules** [comment]
@cjihrig  Except for my inline comment, LGTM.

**Comment by cjihrig** [comment]
Thanks! @misterdjules I updated the comment as you asked. Landed in 1fad3730c2d6130c13b46ad78ded808fe9bb4c10

**Comment by misterdjules** [comment]
@cjihrig @piscisaureus Thanks you!
